# install_roles.yml

# Install roles from Ansible galaxy (https://galaxy.ansible.com/)
# to the project roles.galaxy directory.
#
# ansible-galaxy install --roles-path roles.galaxy -r install_roles.yml
#
# We usually check in the downloaded roles to source control in the project
# to snapshot a working version.

- src: cogini.users
- src: cogini.elixir-release
- src: ANXS.postgresql


# iibrary/iptables_raw.py comes from
# https://github.com/Nordeus/ansible_iptables_raw
